name: Releases

on: 
  push:
    tags:
    - '*'


jobs:
  build:

    runs-on: windows-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build
    - name: Temporarily save Docker image
      uses: actions/upload-artifact@v2
      with:
        name: artifact
        path: "./build/libs"
        retention-days: 1
  release:
    needs: build
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - name: Retrieve saved artifacts
        uses: actions/download-artifact@v2
        with:
          name: artifact
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "artifact/*"



#https://github.com/marketplace/actions/create-release
